# BaselineAnalyzer

Analyzer that is kind to C# beginners.

[![BaselineAnalyzer](Images/BaselineAnalyzer.100.png)](https://github.com/kekyo/BaselineAnalyzer)

----

[![Japanese language](Images/Japanese.256.png)](https://github.com/kekyo/BaselineAnalyzer/blob/main/docs/BLA0002.ja.md)

## BLA0002: Avoid using 'throw ex;' in catch blocks, use 'throw;' instead to preserve stack trace

This occurs when you specify the original exception object,
like `throw ex`, instead of using the `throw` clause when rethrowing an exception:

```csharp
public void Foo()
{
    try
    {
        // Do something...
    }
    catch (Exception ex)
    {
        Console.WriteLine("Caught an exception!");

        // Throw with original exception object...
        throw ex;
    }
}
```

At first glance, this looks fine.
But when you throw like this,
the stack trace information that shows the source of the exception is lost,
and the exception is treated as if it occurred "here".

As a result, an incorrect stack trace is stored in the log when you log the exception,
and the debugger cannot track the correct location where the exception occurred.

If you just want to do something special when an exception occurs,
you can "rethrow" the exception.
This is done using the special `throw` clause:

```csharp
public void Foo()
{
    try
    {
        // Do something...
    }
    catch (Exception ex)
    {
        Console.WriteLine("Caught an exception!");

        // "rethrow" the original exception object
        throw;
    }
}
```
